"""Vendor the three fonts the neo-brutal design names, as local woff2 files.

The design's own page links Google Fonts. This application does not: it is read
on studio machines behind networks that block third-party CDNs, and a stylesheet
request that hangs blocks first paint for as long as the browser is willing to
wait. Vendored, the worst case is a font that is simply there.

Run this to refresh `static/fonts/` and the generated `src/lib/styles/fonts.css`.
It keeps the latin and latin-ext subsets — every glyph this interface prints —
and it de-duplicates: Archivo and Space Grotesk ship as variable fonts, so one
file per subset serves every weight the design asks for.
"""

from __future__ import annotations

import re
import sys
import urllib.request
from pathlib import Path

GOOGLE_CSS = (
    "https://fonts.googleapis.com/css2"
    "?family=Archivo:wght@700;800;900"
    "&family=Space+Grotesk:wght@400;500;700"
    "&family=Space+Mono:wght@400;700"
    "&display=swap"
)
# A current desktop browser, so the API answers with woff2 rather than the ttf
# it hands clients it does not recognise.
USER_AGENT = (
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"
)
SUBSETS = ("latin", "latin-ext")
FACE = re.compile(r"/\* (\S+) \*/\s*(@font-face \{.*?\})", re.S)
TEMPLATE = """@font-face {{
\tfont-family: '{family}';
\tfont-style: normal;
\tfont-weight: {weight};
\tfont-display: swap;
\tsrc: url('/fonts/{file}') format('woff2');
\tunicode-range: {ranges};
}}"""


def fetch(url: str) -> bytes:
    request = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    with urllib.request.urlopen(request, timeout=60) as response:
        return response.read()


def field(block: str, pattern: str) -> str:
    found = re.search(pattern, block)
    if found is None:
        raise ValueError(f"the Google stylesheet no longer carries {pattern!r}")
    return found.group(1)


def parse(css: str) -> dict[str, dict[str, object]]:
    """Group the stylesheet's faces by source file, keeping only our subsets."""
    grouped: dict[str, dict[str, object]] = {}
    for subset, block in FACE.findall(css):
        if subset not in SUBSETS:
            continue
        url = field(block, r"url\((https://[^)]+)\)")
        face = grouped.setdefault(
            url,
            {
                "family": field(block, r"font-family: '([^']+)'"),
                "subset": subset,
                "ranges": field(block, r"unicode-range: ([^;]+);"),
                "weights": [],
            },
        )
        face["weights"].append(int(field(block, r"font-weight: (\d+)")))
    return grouped


def name(face: dict[str, object]) -> str:
    stem = str(face["family"]).lower().replace(" ", "-")
    weights = sorted(face["weights"])
    tail = "" if len(weights) > 1 else f"-{weights[0]}"
    return f"{stem}{tail}-{face['subset']}.woff2"


def weight_of(face: dict[str, object]) -> str:
    weights = sorted(face["weights"])
    return f"{weights[0]} {weights[-1]}" if len(weights) > 1 else str(weights[0])


def main(fonts_dir: Path, stylesheet: Path) -> int:
    fonts_dir.mkdir(parents=True, exist_ok=True)
    faces = parse(fetch(GOOGLE_CSS).decode())
    rendered = []
    for url, face in faces.items():
        file = name(face)
        (fonts_dir / file).write_bytes(fetch(url))
        print(f"vendored {file}", file=sys.stderr)
        rendered.append(
            TEMPLATE.format(
                family=face["family"],
                weight=weight_of(face),
                file=file,
                ranges=face["ranges"],
            )
        )
    stylesheet.write_text(
        "/*\n"
        " * The design's three faces, vendored. GENERATED by\n"
        " * `scripts/vendor_fonts.py` — do not edit by hand.\n"
        " *\n"
        " * Self-hosted deliberately: this interface is read on studio machines\n"
        " * behind networks that block third-party CDNs, and a font request that\n"
        " * hangs costs the page its first paint. `font-display: swap` means a\n"
        " * face that somehow still fails costs the page its voice, never its\n"
        " * layout — the fallback stacks in tokens.css are what it falls back to.\n"
        " *\n"
        " * Archivo, Space Grotesk and Space Mono are all SIL Open Font License\n"
        " * 1.1, which is what permits these files to be redistributed here.\n"
        " */\n\n" + "\n\n".join(rendered) + "\n"
    )
    return 0


if __name__ == "__main__":
    web = Path(__file__).resolve().parents[1]
    raise SystemExit(main(web / "static" / "fonts", web / "src" / "lib" / "styles" / "fonts.css"))
