/**
 * Signing in: authorization code, bound to a proof key this application generates.
 *
 * `auth-integration` fixes the flow for a browser — *"an authorization code
 * exchange bound to a proof key generated by that application"* — and fixes two
 * things this module therefore cannot express: it accepts no password, and
 * there is no parameter anywhere for a client secret, so a browser build cannot
 * embed one. It mirrors `adapters/outbound/auth/flows.py::BrowserSignIn`
 * deliberately, because two implementations of one flow that drift is exactly
 * the class of bug this project keeps refusing to accept.
 *
 * The two halves are split so both are testable with no browser and no issuer:
 * :func:`beginSignIn` produces the address to send the person to and remembers
 * the proof, and :func:`completeSignIn` redeems what comes back. Neither
 * navigates; the route does that, which is what keeps the flow a value and the
 * navigation a detail.
 *
 * **The verifier never leaves this tab.** It is written to the tab's own
 * storage under a key of its own and removed the moment it is redeemed — a
 * single-use proof that outlives exactly one redirect.
 */

import type { SessionStorage } from './storage';
import { HOME, localAddress } from './intent';

export const PENDING_KEY = 'cybercanon.sign-in';
export const DEFAULT_SCOPE = 'openid profile email';
export const CHALLENGE_METHOD = 'S256';
export const AUTHORIZATION_CODE_GRANT = 'authorization_code';

export interface AuthEndpoints {
	readonly authorization: string;
	readonly token: string;
}

export interface SignInConfig {
	readonly endpoints: AuthEndpoints;
	readonly clientId: string;
	readonly redirectUri: string;
	readonly scope?: string;
	readonly audience?: string;
}

/** What one sign-in remembers between the redirect out and the redirect back. */
export interface PendingSignIn {
	readonly state: string;
	readonly verifier: string;
	/** The address the person was going to (`web-session`), carried through. */
	readonly next: string;
}

export interface AuthorizationRequest extends PendingSignIn {
	readonly url: string;
}

/** The token endpoint, as far as this module is concerned. */
export interface Transport {
	post(url: string, form: Record<string, string>): Promise<Record<string, unknown>>;
}

export type SignInOutcome =
	| { readonly kind: 'signed-in'; readonly token: string; readonly next: string }
	/** The issuer answered, and said no. A person can read this and act on it. */
	| { readonly kind: 'refused'; readonly message: string }
	/** Nothing answered, or nothing was in flight. Reads are unaffected. */
	| { readonly kind: 'unavailable'; readonly message: string };

export const NOTHING_PENDING =
	'This sign-in could not be completed because nothing was waiting for it. ' +
	'Start again from the sign-in screen.';

export const WRONG_STATE =
	'This sign-in could not be completed: the answer does not match the request ' +
	'that started it. Start again from the sign-in screen.';

export const NO_TOKEN = 'The identity service issued no credential for this sign-in.';

export interface BeginOptions {
	readonly storage: SessionStorage;
	/** Where the person was going. Validated as a local address before it is kept. */
	readonly next?: string;
	readonly random?: (bytes: number) => Uint8Array;
}

/** The address to send the person to, with the proof remembered for the way back. */
export async function beginSignIn(
	config: SignInConfig,
	options: BeginOptions
): Promise<AuthorizationRequest> {
	const random = options.random ?? randomBytes;
	const verifier = base64Url(random(32));
	const state = base64Url(random(24));
	const next = localAddress(options.next);
	const query = new URLSearchParams({
		response_type: 'code',
		client_id: config.clientId,
		redirect_uri: config.redirectUri,
		scope: config.scope ?? DEFAULT_SCOPE,
		state,
		code_challenge: await challengeFor(verifier),
		code_challenge_method: CHALLENGE_METHOD
	});
	if (config.audience) query.set('audience', config.audience);
	const separator = config.endpoints.authorization.includes('?') ? '&' : '?';
	const pending: PendingSignIn = { state, verifier, next };
	options.storage.write(PENDING_KEY, JSON.stringify(pending));
	return { ...pending, url: `${config.endpoints.authorization}${separator}${query}` };
}

export interface CompleteOptions {
	readonly storage: SessionStorage;
	readonly transport: Transport;
}

/**
 * Redeem what came back from the issuer.
 *
 * The state is compared before anything is sent, and the pending record is
 * dropped whatever happens: a proof that survived a failed exchange would be a
 * proof waiting to be replayed against the next one.
 */
export async function completeSignIn(
	config: SignInConfig,
	url: URL,
	options: CompleteOptions
): Promise<SignInOutcome> {
	const pending = takePending(options.storage);
	const refusal = url.searchParams.get('error');
	if (refusal) return { kind: 'refused', message: describeRefusal(url, refusal) };
	const code = url.searchParams.get('code');
	if (!pending || !code) return { kind: 'unavailable', message: NOTHING_PENDING };
	if (url.searchParams.get('state') !== pending.state) {
		return { kind: 'refused', message: WRONG_STATE };
	}
	return exchange(config, pending, code, options.transport);
}

async function exchange(
	config: SignInConfig,
	pending: PendingSignIn,
	code: string,
	transport: Transport
): Promise<SignInOutcome> {
	try {
		const answer = await transport.post(config.endpoints.token, {
			grant_type: AUTHORIZATION_CODE_GRANT,
			code,
			client_id: config.clientId,
			redirect_uri: config.redirectUri,
			code_verifier: pending.verifier
		});
		const token = credentialIn(answer);
		if (!token) return { kind: 'refused', message: NO_TOKEN };
		return { kind: 'signed-in', token, next: pending.next };
	} catch (failure) {
		// An issuer that answered and said no is a refusal a person can act on;
		// only something that never answered is an outage. Collapsing the two
		// would tell somebody to try again later when the answer will not change.
		if (failure instanceof SignInRefused) return { kind: 'refused', message: failure.message };
		return { kind: 'unavailable', message: unreachable(failure) };
	}
}

/** The pending record, consumed. A proof is single-use by construction. */
export function takePending(storage: SessionStorage): PendingSignIn | null {
	const held = storage.read(PENDING_KEY);
	storage.remove(PENDING_KEY);
	if (!held) return null;
	try {
		const parsed = JSON.parse(held) as Partial<PendingSignIn>;
		if (!parsed.state || !parsed.verifier) return null;
		return { state: parsed.state, verifier: parsed.verifier, next: localAddress(parsed.next) };
	} catch {
		return null;
	}
}

/** A `fetch`-backed token endpoint. The only place this module touches the network. */
export function fetchTransport(fetcher: typeof globalThis.fetch): Transport {
	return {
		async post(url, form) {
			const response = await fetcher(url, {
				method: 'POST',
				headers: { 'Content-Type': 'application/x-www-form-urlencoded', Accept: 'application/json' },
				body: new URLSearchParams(form).toString()
			});
			const body = (await response.json().catch(() => ({}))) as Record<string, unknown>;
			if (!response.ok) throw new SignInRefused(describe(body, response.status));
			return body;
		}
	};
}

export class SignInRefused extends Error {}

function credentialIn(answer: Record<string, unknown>): string | null {
	const token = answer.access_token ?? answer.id_token;
	return typeof token === 'string' && token ? token : null;
}

function describe(body: Record<string, unknown>, status: number): string {
	const described = body.error_description ?? body.error;
	return typeof described === 'string' && described ? described : `the issuer answered ${status}`;
}

function describeRefusal(url: URL, code: string): string {
	const described = url.searchParams.get('error_description');
	return `Sign-in was refused: ${described || code}.`;
}

function unreachable(failure: unknown): string {
	const detail = failure instanceof Error ? failure.message : 'the identity service is unreachable';
	return `Sign-in could not be completed: ${detail}. Reading is unaffected.`;
}

async function challengeFor(verifier: string): Promise<string> {
	const digest = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(verifier));
	return base64Url(new Uint8Array(digest));
}

function randomBytes(count: number): Uint8Array {
	return crypto.getRandomValues(new Uint8Array(count));
}

function base64Url(bytes: Uint8Array): string {
	let binary = '';
	for (const byte of bytes) binary += String.fromCharCode(byte);
	return btoa(binary).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
}

/** The address a completed sign-in returns to when it remembered none. */
export const DEFAULT_RETURN = HOME;
