/**
 * Tasks 3.1, 3.2 and 3.3 — the sign-in itself, both ways in.
 *
 * `auth-integration` fixes the flow — *"an authorization code exchange bound to
 * a proof key generated by that application"* — and fixes two things this suite
 * asserts the way the Python one does for `BrowserSignIn`: no password reaches
 * anything, and there is nowhere for a client secret to be.
 *
 * The in-place half is D5's, and it is the reason the code comes back through a
 * message rather than through a navigation: this tab is still holding somebody's
 * unsaved paragraph, and unloading it to sign in again is exactly the failure
 * the decision exists to prevent.
 */

import { describe, expect, it } from 'vitest';
import {
	AUTHORIZATION_CODE_GRANT,
	CHALLENGE_METHOD,
	NOTHING_PENDING,
	NO_TOKEN,
	PENDING_KEY,
	WRONG_STATE,
	beginSignIn,
	completeSignIn,
	fetchTransport,
	takePending,
	type SignInConfig,
	type Transport
} from '../src/lib/session/oidc';
import {
	CREDENTIAL_MESSAGE,
	TIMED_OUT,
	WINDOW_BLOCKED,
	WINDOW_CLOSED,
	reauthenticateInPlace,
	relaySignIn,
	type MessageSource,
	type Opener,
	type SignInMessage
} from '../src/lib/session/reauthentication';
import { memoryStorage } from '../src/lib/session/storage';
import { mappedPerson } from './support/credentials';

const ORIGIN = 'https://canon.cyberdynecorp.ai';

const CONFIG: SignInConfig = {
	endpoints: {
		authorization: 'https://auth.cyberdynecorp.ai/authorize',
		token: 'https://auth.cyberdynecorp.ai/oauth/token'
	},
	clientId: 'cybercanon-web',
	redirectUri: `${ORIGIN}/signed-in`,
	audience: 'cybercanon'
};

/** Bytes a test can predict, so an address can be compared rather than parsed for shape. */
function counting(): (count: number) => Uint8Array {
	let seed = 1;
	return (count) => Uint8Array.from({ length: count }, (_, index) => (index + seed++) % 251);
}

function issuer(answers: Record<string, unknown>): { transport: Transport; forms: unknown[] } {
	const forms: unknown[] = [];
	return {
		forms,
		transport: {
			async post(_url, form) {
				forms.push(form);
				return answers;
			}
		}
	};
}

describe('starting a sign-in', () => {
	it('sends the person to the issuer with a challenge and a state', async () => {
		const storage = memoryStorage();

		const request = await beginSignIn(CONFIG, { storage, random: counting() });
		const url = new URL(request.url);

		expect(url.origin + url.pathname).toBe(CONFIG.endpoints.authorization);
		expect(url.searchParams.get('response_type')).toBe('code');
		expect(url.searchParams.get('client_id')).toBe('cybercanon-web');
		expect(url.searchParams.get('redirect_uri')).toBe(CONFIG.redirectUri);
		expect(url.searchParams.get('audience')).toBe('cybercanon');
		expect(url.searchParams.get('state')).toBe(request.state);
		expect(url.searchParams.get('code_challenge_method')).toBe(CHALLENGE_METHOD);
	});

	it('sends the challenge and keeps the verifier, which is the whole point', async () => {
		const storage = memoryStorage();

		const request = await beginSignIn(CONFIG, { storage, random: counting() });
		const url = new URL(request.url);

		expect(url.searchParams.get('code_challenge')).toBe(await challengeFor(request.verifier));
		expect(request.url).not.toContain(request.verifier);
		expect(JSON.parse(storage.read(PENDING_KEY) ?? '{}').verifier).toBe(request.verifier);
	});

	it('carries no password and no secret, because it has nowhere to put one', async () => {
		const request = await beginSignIn(CONFIG, { storage: memoryStorage() });

		expect(request.url).not.toMatch(/password|client_secret|secret=/i);
	});

	it('remembers where the person was going, validated before it is kept', async () => {
		const storage = memoryStorage();

		await beginSignIn(CONFIG, { storage, next: '/p/ironwood/a/mech_scout' });
		const kept = takePending(storage);

		expect(kept?.next).toBe('/p/ironwood/a/mech_scout');
	});

	it('refuses to remember somebody else’s origin as the way back', async () => {
		const storage = memoryStorage();

		await beginSignIn(CONFIG, { storage, next: 'https://evil.example/harvest' });

		expect(takePending(storage)?.next).toBe('/');
	});
});

describe('coming back from the issuer', () => {
	async function started(next = '/p/ironwood/a/mech_scout') {
		const storage = memoryStorage();
		const request = await beginSignIn(CONFIG, { storage, next, random: counting() });
		return { storage, request };
	}

	function returned(state: string, parameters: Record<string, string> = {}): URL {
		const url = new URL(CONFIG.redirectUri);
		url.searchParams.set('code', 'the-code');
		url.searchParams.set('state', state);
		for (const [name, value] of Object.entries(parameters)) url.searchParams.set(name, value);
		return url;
	}

	it('redeems the code with the verifier, and arrives where the person was going', async () => {
		const { storage, request } = await started();
		const token = mappedPerson();
		const { transport, forms } = issuer({ access_token: token });

		const outcome = await completeSignIn(CONFIG, returned(request.state), { storage, transport });

		expect(outcome).toEqual({ kind: 'signed-in', token, next: '/p/ironwood/a/mech_scout' });
		expect(forms).toEqual([
			{
				grant_type: AUTHORIZATION_CODE_GRANT,
				code: 'the-code',
				client_id: CONFIG.clientId,
				redirect_uri: CONFIG.redirectUri,
				code_verifier: request.verifier
			}
		]);
	});

	it('refuses an answer whose state is not the one it sent', async () => {
		const { storage } = await started();
		const { transport, forms } = issuer({ access_token: mappedPerson() });

		const outcome = await completeSignIn(CONFIG, returned('somebody-else’s-state'), {
			storage,
			transport
		});

		expect(outcome).toEqual({ kind: 'refused', message: WRONG_STATE });
		expect(forms).toEqual([]);
	});

	it('spends the proof once: a replayed return finds nothing waiting', async () => {
		const { storage, request } = await started();
		const { transport } = issuer({ access_token: mappedPerson() });
		await completeSignIn(CONFIG, returned(request.state), { storage, transport });

		const again = await completeSignIn(CONFIG, returned(request.state), { storage, transport });

		expect(again).toEqual({ kind: 'unavailable', message: NOTHING_PENDING });
	});

	it('states the issuer’s own refusal rather than inventing one', async () => {
		const { storage, request } = await started();
		const { transport } = issuer({});
		const refused = returned(request.state, {
			error: 'access_denied',
			error_description: 'the person cancelled'
		});

		const outcome = await completeSignIn(CONFIG, refused, { storage, transport });

		expect(outcome).toMatchObject({ kind: 'refused' });
		expect(outcome.kind === 'refused' && outcome.message).toContain('the person cancelled');
	});

	it('refuses an exchange that produced no credential', async () => {
		const { storage, request } = await started();
		const { transport } = issuer({ token_type: 'Bearer' });

		const outcome = await completeSignIn(CONFIG, returned(request.state), { storage, transport });

		expect(outcome).toEqual({ kind: 'refused', message: NO_TOKEN });
	});

	it('degrades rather than throwing when the issuer cannot be reached', async () => {
		const { storage, request } = await started();
		const transport: Transport = {
			async post() {
				throw new TypeError('fetch failed: ECONNREFUSED');
			}
		};

		const outcome = await completeSignIn(CONFIG, returned(request.state), { storage, transport });

		expect(outcome).toMatchObject({ kind: 'unavailable' });
		expect(outcome.kind === 'unavailable' && outcome.message).toContain('Reading is unaffected');
	});

	it('posts the exchange as a form, which is what a token endpoint reads', async () => {
		const calls: { url: string; init: RequestInit }[] = [];
		const fetcher = (async (url: string, init: RequestInit) => {
			calls.push({ url: String(url), init });
			return new Response(JSON.stringify({ access_token: 'tok' }), { status: 200 });
		}) as unknown as typeof fetch;

		await fetchTransport(fetcher).post(CONFIG.endpoints.token, { code: 'c' });

		expect(calls[0].url).toBe(CONFIG.endpoints.token);
		expect(calls[0].init.method).toBe('POST');
		expect(calls[0].init.body).toBe('code=c');
	});

	it('turns a refusing token endpoint into a described failure', async () => {
		const fetcher = (async () =>
			new Response(JSON.stringify({ error_description: 'code already used' }), {
				status: 400
			})) as unknown as typeof fetch;

		await expect(fetchTransport(fetcher).post(CONFIG.endpoints.token, {})).rejects.toThrow(
			'code already used'
		);
	});
});

describe('re-authenticating without leaving the page', () => {
	/**
	 * A browser, as far as this flow needs one: a window that can be opened and
	 * something that delivers messages. The fake reads the state out of the
	 * address it is asked to open, exactly as the real second window would have
	 * it handed back by the issuer, so the state comparison is really exercised
	 * rather than stubbed past.
	 */
	function fakeBrowser(options: { answers?: SignInMessage | 'echo'; closed?: boolean; from?: string } = {}) {
		const listeners = new Set<(event: MessageEvent) => void>();
		const opened: string[] = [];
		const messages: MessageSource = {
			addEventListener: (_type, listener) => void listeners.add(listener),
			removeEventListener: (_type, listener) => void listeners.delete(listener)
		};
		const deliver = (data: SignInMessage) => {
			setTimeout(() => {
				for (const listener of [...listeners]) {
					listener({ origin: options.from ?? ORIGIN, data } as MessageEvent);
				}
			}, 0);
		};
		const opener: Opener = {
			open(url) {
				opened.push(url);
				const state = new URL(url).searchParams.get('state') ?? '';
				if (options.answers === 'echo') {
					deliver({ type: CREDENTIAL_MESSAGE, code: 'the-code', state });
				} else if (options.answers) {
					deliver(options.answers);
				}
				return { closed: options.closed ?? false, close: () => {} };
			}
		};
		return { opener, messages, opened };
	}

	function waiting(browser: ReturnType<typeof fakeBrowser>, transport: Transport, times = {}) {
		return reauthenticateInPlace(CONFIG, {
			opener: browser.opener,
			messages: browser.messages,
			storage: memoryStorage(),
			transport,
			origin: ORIGIN,
			pollMs: 1000,
			timeoutMs: 200,
			...times
		});
	}

	it('opens the issuer without navigating this page anywhere', async () => {
		const browser = fakeBrowser({ answers: 'echo' });

		await waiting(browser, issuer({ access_token: mappedPerson() }).transport);

		expect(browser.opened).toHaveLength(1);
		expect(browser.opened[0].startsWith(CONFIG.endpoints.authorization)).toBe(true);
	});

	it('redeems the code the second window handed back, in the tab that holds the proof', async () => {
		const token = mappedPerson();
		const { transport, forms } = issuer({ access_token: token });

		const outcome = await waiting(fakeBrowser({ answers: 'echo' }), transport);

		expect(outcome).toEqual({ kind: 'signed-in', token, next: '/' });
		expect(forms).toHaveLength(1);
		expect((forms[0] as Record<string, string>).code).toBe('the-code');
		expect((forms[0] as Record<string, string>).code_verifier).toBeTruthy();
	});

	it('refuses an answer whose state is not the one this tab sent', async () => {
		const browser = fakeBrowser({
			answers: { type: CREDENTIAL_MESSAGE, code: 'the-code', state: 'not-the-one' }
		});

		const outcome = await waiting(browser, issuer({ access_token: mappedPerson() }).transport);

		expect(outcome).toEqual({ kind: 'refused', message: WRONG_STATE });
	});

	it('ignores a message from any other origin', async () => {
		const browser = fakeBrowser({ answers: 'echo', from: 'https://evil.example' });

		const outcome = await waiting(browser, issuer({ access_token: mappedPerson() }).transport, {
			timeoutMs: 20
		});

		expect(outcome).toEqual({ kind: 'unavailable', message: TIMED_OUT });
	});

	it('says so when the window could not be opened, and holds nothing against the person', async () => {
		const outcome = await reauthenticateInPlace(CONFIG, {
			opener: { open: () => null },
			messages: fakeBrowser().messages,
			storage: memoryStorage(),
			transport: issuer({}).transport,
			origin: ORIGIN
		});

		expect(outcome).toEqual({ kind: 'unavailable', message: WINDOW_BLOCKED });
	});

	it('says so when the window was closed before a credential arrived', async () => {
		const outcome = await waiting(fakeBrowser({ closed: true }), issuer({}).transport, {
			pollMs: 1,
			timeoutMs: 500
		});

		expect(outcome).toEqual({ kind: 'unavailable', message: WINDOW_CLOSED });
	});

	it('stops waiting eventually, rather than holding a prompt open forever', async () => {
		const outcome = await waiting(fakeBrowser(), issuer({}).transport, { timeoutMs: 10 });

		expect(outcome).toEqual({ kind: 'unavailable', message: TIMED_OUT });
	});
});

describe('the second window', () => {

	it('hands back the code and the state, to this application’s origin only', () => {
		const posted: { message: SignInMessage; origin: string }[] = [];
		const url = new URL(`${ORIGIN}/signed-in?code=the-code&state=the-state`);

		relaySignIn(url, { postMessage: (message, origin) => posted.push({ message, origin }) }, ORIGIN);

		expect(posted).toEqual([
			{
				message: { type: CREDENTIAL_MESSAGE, code: 'the-code', state: 'the-state' },
				origin: ORIGIN
			}
		]);
	});

	it('hands back a refusal too, so the prompt can say what happened', () => {
		const posted: SignInMessage[] = [];
		const url = new URL(`${ORIGIN}/signed-in?error=access_denied&error_description=cancelled`);

		relaySignIn(url, { postMessage: (message) => posted.push(message) }, ORIGIN);

		expect(posted[0]).toEqual({
			type: CREDENTIAL_MESSAGE,
			error: 'access_denied',
			error_description: 'cancelled'
		});
	});

	it('never carries a credential, because it never had one', () => {
		const posted: SignInMessage[] = [];

		relaySignIn(
			new URL(`${ORIGIN}/signed-in?code=c&state=s`),
			{ postMessage: (message) => posted.push(message) },
			ORIGIN
		);

		expect(JSON.stringify(posted[0])).not.toContain('token');
	});
});


async function challengeFor(verifier: string): Promise<string> {
	const digest = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(verifier));
	return base64Url(new Uint8Array(digest));
}

function base64Url(bytes: Uint8Array): string {
	let binary = '';
	for (const byte of bytes) binary += String.fromCharCode(byte);
	return btoa(binary).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
}
