"""Proof of possession for the browser sign-in — the key the application keeps.

`auth-integration`: *"a person signing in through a browser-based application
SHALL do so by an authorization-code exchange bound to a proof key generated by
that application ... no confidential client secret SHALL be required by or
embedded in a browser-delivered application."*

That is PKCE, and the reason it replaces a client secret is the reason it is
here rather than in configuration: a secret shipped inside a page that anyone can
read is not a secret, whereas a proof key is generated per sign-in, never leaves
the application, and is useless to anyone who intercepts the redirect.

:class:`ProofKey` is the pair. The application keeps `verifier` and sends
`challenge`; the issuer remembers the challenge against the code it issued and
will only exchange that code for a credential when the matching verifier comes
back. :func:`verify` is that comparison, written here because it is the other
half of the same primitive and because it is what makes the requirement
testable: an exchange presented without the verifier does not produce a
credential, and the assertion needs the check the issuer performs.
"""

from __future__ import annotations

import hashlib
import secrets
from base64 import urlsafe_b64encode
from dataclasses import dataclass, field

METHOD = "S256"
"""The only challenge method offered. `plain` exists and is not proof of anything."""

MINIMUM_VERIFIER_LENGTH = 43
MAXIMUM_VERIFIER_LENGTH = 128


def _b64(raw: bytes) -> str:
    return urlsafe_b64encode(raw).decode("ascii").rstrip("=")


@dataclass(frozen=True)
class ProofKey:
    """A sign-in's proof of possession: the secret half and the public half.

    `verifier` is excluded from the generated `repr`, for the reason every
    secret in this repository is: a value that prints is a value that reaches a
    log line, and a leaked verifier turns an intercepted authorization code back
    into a session.
    """

    verifier: str = field(repr=False)

    def __post_init__(self) -> None:
        if not MINIMUM_VERIFIER_LENGTH <= len(self.verifier) <= MAXIMUM_VERIFIER_LENGTH:
            raise ValueError(
                "a proof key's verifier is between "
                f"{MINIMUM_VERIFIER_LENGTH} and {MAXIMUM_VERIFIER_LENGTH} characters"
            )

    @classmethod
    def generate(cls) -> ProofKey:
        """A fresh proof key, from the system's cryptographic random source."""
        return cls(verifier=_b64(secrets.token_bytes(64)))

    @property
    def challenge(self) -> str:
        """What the application sends with the authorization request."""
        return _b64(hashlib.sha256(self.verifier.encode("ascii")).digest())

    @property
    def method(self) -> str:
        return METHOD

    def __str__(self) -> str:
        return "<proof key>"


def verify(challenge: str, verifier: str, method: str = METHOD) -> bool:
    """Whether this verifier is the one the challenge was derived from.

    The check the issuer performs, compared in constant time. An unrecognised
    method is false rather than an error: refusing to compare is the safe
    answer, and `plain` is not a method this application ever offers.
    """
    if method != METHOD:
        return False
    expected = _b64(hashlib.sha256(verifier.encode("ascii")).digest())
    return secrets.compare_digest(expected, challenge)


__all__ = [
    "MAXIMUM_VERIFIER_LENGTH",
    "METHOD",
    "MINIMUM_VERIFIER_LENGTH",
    "ProofKey",
    "verify",
]
