"""Generate the committed ``.feature`` tree from the spec deltas (D1).

The output is committed so diffs are reviewable and step definitions can point at
real files, and it is regenerated by ``just features`` — which CI reaches through
``just check`` — so a hand edit cannot survive. Generation is deterministic: the
same specs produce byte-identical files, every time, in a fixed order.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from canon_bdd import gherkin
from canon_bdd.specs import CapabilitySpec, load_all

FEATURES_DIR = Path("tests/bdd/features")
OPENSPEC_DIR = Path("openspec")
FEATURE_SUFFIX = ".feature"


@dataclass(frozen=True)
class Difference:
    """One committed feature file that does not match the specs."""

    path: Path
    reason: str

    def __str__(self) -> str:
        return f"{self.path.as_posix()}: {self.reason}"


def load_specs(repo_root: Path) -> tuple[CapabilitySpec, ...]:
    """Every spec delta, parsed, in a deterministic order."""
    return load_all(repo_root / OPENSPEC_DIR, repo_root)


def generate(repo_root: Path) -> dict[Path, str]:
    """The feature tree the current specs imply: repo-relative path -> file text."""
    return {spec.feature_path: gherkin.render(spec) for spec in load_specs(repo_root)}


def write(repo_root: Path) -> tuple[Path, ...]:
    """Write the feature tree, removing features whose spec is gone."""
    expected = generate(repo_root)
    for path in _committed(repo_root) - set(expected):
        (repo_root / path).unlink()
    for path, text in expected.items():
        target = repo_root / path
        target.parent.mkdir(parents=True, exist_ok=True)
        if not target.exists() or target.read_text(encoding="utf-8") != text:
            target.write_text(text, encoding="utf-8")
    _prune_empty_directories(repo_root / FEATURES_DIR)
    return tuple(sorted(expected))


def check(repo_root: Path) -> tuple[Difference, ...]:
    """Differences between the committed feature tree and the specs (D1)."""
    expected = generate(repo_root)
    committed = _committed(repo_root)
    stale = [
        Difference(path, "not generated from any spec delta; delete it")
        for path in sorted(committed - set(expected))
    ]
    drifted = [
        difference
        for path, text in sorted(expected.items())
        if (difference := _difference(repo_root, path, text)) is not None
    ]
    return (*stale, *drifted)


def _difference(repo_root: Path, path: Path, text: str) -> Difference | None:
    target = repo_root / path
    if not target.is_file():
        return Difference(path, "missing; run `just gen-features`")
    if target.read_text(encoding="utf-8") != text:
        return Difference(path, "differs from its spec delta; run `just gen-features`")
    return None


def _committed(repo_root: Path) -> set[Path]:
    root = repo_root / FEATURES_DIR
    if not root.is_dir():
        return set()
    return {path.relative_to(repo_root) for path in root.rglob(f"*{FEATURE_SUFFIX}")}


def _prune_empty_directories(root: Path) -> None:
    if not root.is_dir():
        return
    for directory in sorted(root.rglob("*"), reverse=True):
        if directory.is_dir() and not any(directory.iterdir()):
            directory.rmdir()
